### ISSUE TITLE
Request for Dataset Used in Your Publication

### ISSUE THREAD

**Issue by Symnluckea** [tkkxgh/DVIMC-pytorch#1]
Hello. The dataset "Multi-Fashion.npz" used in your study, appears to be an invaluable resource for my ongoing research. I am writing to kindly request access to this dataset, or any relevant subsets that you may be able to share. Thank you very much for considering my request.

**Comment by tkkxgh** [comment]
https://pan.baidu.com/s/178mgz-1zrTyXM5EQiepO0Q&nbsp;&nbsp;je2t




Kagome
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tkkxgh/DVIMC-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月12日(星期六) 中午11:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tkkxgh/DVIMC-pytorch] Request for Dataset Used in Your Publication (Issue #1)





 
Hello. The dataset "Multi-Fashion.npz" used in your study, appears to be an invaluable resource for my ongoing research. I am writing to kindly request access to this dataset, or any relevant subsets that you may be able to share. Thank you very much for considering my request.

**Comment by Symnluckea** [comment]
Thank you for your support. I wish you continued success in your research endeavors！
